apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bitcoin-etl-streaming
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bitcoin-etl-streaming
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: bitcoin-etl-app-key
      - name: last-synced-block
        emptyDir: {}
      initContainers:
      - name: download-last-synced-block-file
        image: google/cloud-sdk:220.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://$(GCS_BUCKET)/$(CHAIN)-etl/streaming/last_synced_block.txt
        - /var/bitcoin-etl/last_synced_block.txt
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: last-synced-block
          mountPath: /var/bitcoin-etl
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: GCS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: bitcoin-etl-config
              key: GCS_BUCKET
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: bitcoin-etl-streaming
        image: blockchainetl/bitcoin-etl:1.0-streaming
        args:
          - "stream"
          - "--provider-uri=$(PROVIDER_URI)"
          - "--last-synced-block-file=/var/bitcoin-etl/last_synced_block.txt"
          - "--output=$(PUBSUB_TOPIC)"
          - "--chain=$(CHAIN)"
          - "--lag=2"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: last-synced-block
          mountPath: /var/bitcoin-etl
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: PUBSUB_TOPIC
          valueFrom:
            configMapKeyRef:
              name: bitcoin-etl-config
              key: PUBSUB_TOPIC
        - name: CHAIN
          valueFrom:
            configMapKeyRef:
              name: bitcoin-etl-config
              key: CHAIN
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "350m"
      - name: upload-last-synced-block-file
        image: google/cloud-sdk:220.0.0-alpine
        command:
        - watch
        - "-n"
        - "60"
        - gsutil
        - cp
        - /var/bitcoin-etl/last_synced_block.txt
        - gs://$(GCS_BUCKET)/$(CHAIN)-etl/streaming/last_synced_block.txt
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: last-synced-block
          mountPath: /var/bitcoin-etl
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: GCS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: bitcoin-etl-config
              key: GCS_BUCKET
        - name: CHAIN
          valueFrom:
            configMapKeyRef:
              name: bitcoin-etl-config
              key: CHAIN
        lifecycle:
          preStop:
            exec:
              command:
              - gsutil
              - cp
              - /var/bitcoin-etl/last_synced_block.txt
              - gs://$(GCS_BUCKET)/$(CHAIN)-etl/streaming/last_synced_block.txt
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

