apiVersion: v1
kind: ConfigMap
metadata:
  name: etl-streaming-config
data:
  PROVIDER_URI: "http://user:pass@localhost:8332"
  GCS_BUCKET: "your-bucket"
  PUB_SUB_TOPIC_PREFIX: "projects/your-project/topics/crypto_bitcoin"
  CHAIN: "bitcoin"
  LAG_BLOCKS: "2"
  MAX_WORKERS: "4"