apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: etl-streaming
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etl-streaming
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: bitcoin-etl-app-key
      - name: last-synced-block
        emptyDir: {}
      initContainers:
      - name: download-last-synced-block-file
        image: google/cloud-sdk:220.0.0-alpine
        command:
        - gsutil
        - cp
        - gs://$(gcsBucket)/$(chain)-etl/streaming/last_synced_block.txt
        - /var/bitcoin-etl/last_synced_block.txt
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: last-synced-block
          mountPath: /var/bitcoin-etl
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: gcsBucket
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: gcsBucket
        - name: chain
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: chain
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: bitcoin-etl-streaming
        image: blockchainetl/bitcoin-etl:1.0-streaming
        args:
          - "stream"
          - "--provider-uri=$(providerUri)"
          - "--last-synced-block-file=/var/bitcoin-etl/last_synced_block.txt"
          - "--output=$(pubSubTopicPrefix)"
          - "--chain=$(chain)"
          - "--lag=$(lagBlocks)"
          - "--max-workers=$(maxWorkers)"
          - "--batch-size=5"
          - "--block-batch-size=1"
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: last-synced-block
          mountPath: /var/bitcoin-etl
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: providerUri
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: providerUri
        - name: pubSubTopicPrefix
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: pubSubTopicPrefix
        - name: chain
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: chain
        - name: lagBlocks
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: lagBlocks
        - name: maxWorkers
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: maxWorkers
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "350m"
      - name: upload-last-synced-block-file
        image: google/cloud-sdk:220.0.0-alpine
        command:
        - watch
        - "-n"
        - "60"
        - gsutil
        - cp
        - /var/bitcoin-etl/last_synced_block.txt
        - gs://$(gcsBucket)/$(chain)-etl/streaming/last_synced_block.txt
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: last-synced-block
          mountPath: /var/bitcoin-etl
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        - name: gcsBucket
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: gcsBucket
        - name: chain
          valueFrom:
            configMapKeyRef:
              name: etl-streaming-config
              key: chain
        lifecycle:
          preStop:
            exec:
              command:
              - gsutil
              - cp
              - /var/bitcoin-etl/last_synced_block.txt
              - gs://$(gcsBucket)/$(chain)-etl/streaming/last_synced_block.txt
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

